import numpy as np
import pygad
import argparse
import csv
import random
import math


ACCEPTABLE_POPULATION_RANGE = 1.2 # acceptable ratio between state's min:max population district. i.e. 1.2 means 1.2 * min >= max
STATE = "tennessee" #for filepath
NUM_DISTRICTS = 9
REPUBLICAN_DISTRICTS = 6 #treat democrat as num_districts - republican_districts, 2 variables seems less good
#taken from predict.py
def load_csv(path):
    rows = []
    with open(path, "r", newline="") as f:
        reader = csv.reader(f, quoting=csv.QUOTE_NONNUMERIC)
        for row in reader:
            rows.append(row)
    return np.array(rows, dtype=np.float64)

def determine_republican_districts(districts): # gets # republican districts. Treat democrat as n-return value
    num_r_districts = 0
    for district in districts:
        sum_values = np.sum(district, axis=0)# 0-3 id, lat, lon, pop. 4=R, 5=D
        if sum_values[4] > sum_values[5]: #R_vote > D_vote
            num_r_districts += 1
    return num_r_districts


def get_population_per_district(districts): # array of population per district
    populations = []
    for district in districts:
        sum_values = np.sum(district, axis=0) # 3 = pop
        populations.append(sum_values[3])
    populations_np = np.array(populations)
    return populations_np
    

def equal_population_districts(blocks, num_districts=NUM_DISTRICTS, # method generated by Claude Sonnet 4.6
                                rotation_deg=0, num_strips=None):
    """
    Strip/snake district seeder. Sort by (rotated) latitude into
    strips, sort each strip by longitude (alternating direction),
    cut each into equal-population segments.
 
    rotation_deg : rotates the lon/lat plane before sorting. 0 =
                   horizontal strips, 90 = vertical, anything between
                   = diagonal. Randomize this per GA individual for
                   shape variety -- population balance stays exact.
    num_strips   : override the default round(sqrt(num_districts)).
    """
    theta = math.radians(rotation_deg)
    cos_a, sin_a = math.cos(theta), math.sin(theta)
    rotated = [(b[1] * cos_a - b[2] * sin_a, b[1] * sin_a + b[2] * cos_a) for b in blocks]
 
    order = sorted(range(len(blocks)), key=lambda i: rotated[i][1])
    blocks = [blocks[i] for i in order]
    rotated = [rotated[i] for i in order]
 
    num_strips = num_strips or max(1, round(num_districts ** 0.5))
    base, rem = divmod(num_districts, num_strips)
    strip_district_counts = [base + (1 if i < rem else 0) for i in range(num_strips)]
 
    def cuts_for(pops, n_chunks):
        cum = np.cumsum(pops)
        total = cum[-1] if len(cum) else 0
        return [0] + [int(np.searchsorted(cum, total * k / n_chunks)) for k in range(1, n_chunks)] + [len(pops)]
 
    pops = np.array([b[3] for b in blocks], dtype=float)
    strip_cuts = cuts_for(pops, num_strips)
 
    districts = []
    for s in range(num_strips):
        lo, hi = strip_cuts[s], strip_cuts[s + 1]
        strip, strip_rot = blocks[lo:hi], rotated[lo:hi]
        d_count = strip_district_counts[s]
 
        strip_order = sorted(range(len(strip)), key=lambda i: strip_rot[i][0], reverse=(s % 2 == 1))
        strip = [strip[i] for i in strip_order]
 
        strip_pops = np.array([b[3] for b in strip], dtype=float)
        d_cuts = cuts_for(strip_pops, d_count)
        for d in range(d_count):
            districts.append(strip[d_cuts[d]:d_cuts[d + 1]])
 
    for d in districts:
        if not d:
            d.append([0, 0, 0, 0, 0, 0])
    return districts

def get_district_centroids(districts): # centers of all districts[[lon, lat] ...]
    centroids = []
    for district in districts:
        lons = district[:, 1]
        lats = district[:, 2]
        center_lon = (max(lons) + min(lons)) / 2
        center_lat = (max(lats) + min(lats)) / 2
        centroids.append([center_lon, center_lat])
    centroids_np = np.array(centroids)
    return centroids_np


        

def fitness_func(ga_instance, solution, solution_idx): #rewards closer seats and more population spread without being over limit
    seat_difference = abs(determine_republican_districts(solution) - REPUBLICAN_DISTRICTS)
    district_main_value = NUM_DISTRICTS - seat_difference # higher number when seats closer to desired
    pops = get_population_per_district(solution)
    population_ratio = max(pops) / min(pops)
    if population_ratio <= ACCEPTABLE_POPULATION_RANGE: #good maps tend to have some disparity in population but not too much. Helps to encourage some changes but less than a seat's worth
        district_main_value += (population_ratio - 1)
    else:
        district_main_value = district_main_value - (population_ratio - 1) # seats matter more but still punish incorrect population distribution
    return district_main_value


def main():
    #ap = argparse.ArgumentParser()
    #ap.add_argument("predict_csv") # where to get data from
    #ap.add_argument("districts_csv") # where to print district mappings to
    #args = ap.parse_args()

    predicted_data = load_csv("D:/AIProj1/predict_data/" + STATE +"_predict.csv")


    for data in predicted_data:
        data[6] = round(data[4] * data[6]) #d_vote * num_votes
        data[5] = round(data[4] * data[5]) #r_vote * num_votes,
    predicted_data = np.delete(predicted_data, 4, axis=1) # trim off num votes column
    #new shape is [id, long, lat, pop, republican_votes, democrat_votes]
    #worth noting btw that the total is often 1-2 less than the expected vote amount because of rounding. Could do ceiling and have it be more also
    
    districts = equal_population_districts(predicted_data)
    districts_2 = equal_population_districts(predicted_data, num_strips= 2, rotation_deg= 63)
    print(fitness_func(None, districts, None))
    print(fitness_func(None, districts_2, None))
    print(determine_republican_districts(districts))
    print(determine_republican_districts(districts_2))

    
    

    





if __name__ == "__main__":
    main()
